export const Elements = [
    {
        Name: "SAND",
        Color: "rgb(194, 178, 128)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 1700,
        BoilingPoint: 2230,
        ColdType: "Powder",
        HotType: "Liquid",
        Type: "Powder",
        Category: "Powder",
        Flair: "Powder"
    },
    {
        Name: "WATR",
        Color: "rgb(15, 94, 156)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 32,
        MeltingPoint: 100,
        BoilingPoint: 100,
        ColdType: "Liquid",
        HotType: "Gas",
        Type: "Liquid",
        Category: "Liquid",
        Flair: "Liquid"
    },
    {
        Name: "LAVA",
        Color: "rgb(207, 16, 32)",
        Flammable: false,
        Caustic: true,
        Radioactive: false,
        Light: false,
        Temp: 1250,
        MeltingPoint: 700,
        BoilingPoint: 2400,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Liquid",
        Category: "Liquid",
        Flair: "Liquid"
    },
    {
        Name: "COAL",
        Color: "rgb(68, 69, 69)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: window.Infinity,
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "WOOD",
        Color: "rgb(218, 109, 66)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: window.Infinity,
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "IRON",
        Color: "rgb(60, 60, 60)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 1538,
        BoilingPoint: 2862,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "TUNG",
        Color: "rgb(150, 150, 150)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 3422,
        BoilingPoint: 5555,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "STAN",
        Color: "rgb(145, 145, 145)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 231.9,
        BoilingPoint: 2602,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "BRCK",
        Color: "rgb(90, 90, 90)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 780,
        BoilingPoint: 2980,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "GLAS",
        Color: "rgb(60, 60, 60)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 1500,
        BoilingPoint: 2230,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "GOLD",
        Color: "rgb(255, 165, 0)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 1064,
        BoilingPoint: 2836,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "DMND",
        Color: "rgb(55, 200, 200)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 3550,
        BoilingPoint: 7500,
        ColdType: "Solid",
        HotType: "Powder",
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "TTAN",
        Color: "rgb(144, 144, 144)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 1668,
        BoilingPoint: 3287,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "SNOW",
        Color: "rgb(134, 214, 216)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 0,
        MeltingPoint: 3,
        BoilingPoint: 100,
        ColdType: "Powder",
        HotType: "Liquid",
        Type: "Powder",
        Category: "Powder",
        Flair: "Powder"
    },
    {
        Name: "POLO",
        Color: "rgb(80, 96, 48)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Radioactivity: 4,
        Light: false,
        Temp: 46,
        MeltingPoint: 254,
        BoilingPoint: 962,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Powder",
        Category: "Powder",
        Flair: "Radioactive Powder"
    },
    {
        Name: "URAN",
        Color: "rgb(112, 112, 32)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Radioactivity: 1,
        Light: false,
        Temp: 46,
        MeltingPoint: 1132,
        BoilingPoint: 4131,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Powder",
        Category: "Powder",
        Flair: "Radioactive Powder"
    },
    {
        Name: "ROEN",
        Color: "rgb(100, 124, 32)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Radioactivity: 8,
        Light: false,
        Temp: 46,
        MeltingPoint: 822,
        BoilingPoint: 1527,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Powder",
        Category: "Powder",
        Flair: "Radioactive Powder"
    },
    {
        Name: "PLUT",
        Color: "rgb(70, 150, 22)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Radioactivity: 2,
        Light: false,
        Temp: 46,
        MeltingPoint: 639.4,
        BoilingPoint: 3232,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Powder",
        Category: "Powder",
        Flair: "Radioactive Powder"
    },
    {
        Name: "OGAN",
        Color: "rgb(57, 200, 20)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Radioactivity: 18,
        Light: false,
        Temp: 46,
        MeltingPoint: 343,
        BoilingPoint: 912,
        ColdType: "Solid",
        HotType: "Liquid",
        Type: "Powder",
        Category: "Powder",
        Flair: "Radioactive Powder"
    },
    {
        Name: "NEUT",
        Color: "rgb(32, 224, 255)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: true,
        Temp: 22,
        Type: "None",
        Category: "None",
        Flair: "Light"
    },
    {
        Name: "PHOT",
        Color: "rgb(255, 255, 255)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: true,
        Temp: 1250,
        Type: "None",
        Category: "None",
        Flair: "Light"
    },
    {
        Name: "STNE",
        Color: "rgb(155, 155, 155)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 1100,
        BoilingPoint: 1648.9,
        ColdType: "Powder",
        HotType: "Liquid",
        Type: "Powder",
        Category: "Powder",
        Flair: "Powder"
    },
    {
        Name: "SALT",
        Color: "rgb(225, 225, 225)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        MeltingPoint: 801,
        BoilingPoint: 1413,
        ColdType: "Powder",
        HotType: "Liquid",
        Type: "Powder",
        Category: "Powder",
        Flair: "Powder"
    },
    {
        Name: "RADO",
        Color: "rgb(155, 255, 155)",
        Flammable: true,
        Caustic: false,
        Radioactive: true,
        Radioactivity: 24,
        Light: false,
        Temp: 46,
        Type: "Gas",
        Category: "Gas",
        Flair: "Radioactive Gas"
    },
    {
        Name: "PLSM",
        Color: "rgb(225, 100, 200)",
        Flammable: false,
        Caustic: true,
        Radioactive: false,
        Light: false,
        Temp: 11326.85,
        MeltingPoint: window.Infinity,
        BoilingPoint: window.Infinity,
        Type: "Gas",
        Category: "Gas",
        Flair: "Gas"
    },
    {
        Name: "OXYG",
        Color: "rgb(200, 200, 255)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Gas",
        Category: "Gas",
        Flair: "Gas"
    },
    {
        Name: "HYGN",
        Color: "rgb(80, 112, 255)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Gas",
        Category: "Gas",
        Flair: "Gas"
    },
    {
        Name: "FIRE",
        Color: "rgb(255, 50, 50)",
        Flammable: false,
        Caustic: true,
        Radioactive: false,
        Light: false,
        Temp: 1100,
        Type: "Gas",
        Category: "Gas",
        Flair: "Caustic Gas"
    },
    {
        Name: "SMKE",
        Color: "rgb(100, 100, 100)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 149,
        Type: "Gas",
        Category: "Gas",
        Flair: "Gas"
    },
    {
        Name: "NONE",
        Color: "rgb(0, 0, 0)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 0,
        Type: "None",
        Category: "None",
        Flair: "None"
    }
];