export const Elements = [
    {
        Name: "SAND",
        Color: "rgb(194, 178, 128)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Powder",
        Category: "Powder",
        Description: "Granular material."
    },
    {
        Name: "WATR",
        Color: "rgb(15, 94, 156)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Liquid",
        Category: "Liquid",
        Description: "Essential liquid."
    },
    {
        Name: "COAL",
        Color: "rgb(68, 69, 69)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Description: "Combustible rock."
    },
    {
        Name: "WOOD",
        Color: "rgb(218, 109, 66)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Description: "Flammable tree material."
    },
    {
        Name: "IRON",
        Color: "rgb(60, 60, 60)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Description: "Strong metal."
    },
    {
        Name: "BRCK",
        Color: "rgb(90, 90, 90)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Description: "Clay brick."
    },
    {
        Name: "URAN",
        Color: "rgb(112, 112, 32)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Light: false,
        Temp: 46,
        Type: "Powder",
        Category: "Powder",
        Description: "Radioactive metal powder."
    },
    {
        Name: "ROEN",
        Color: "rgb(100, 124, 32)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Light: false,
        Temp: 46,
        Type: "Powder",
        Category: "Powder",
        Description: "Radioactive powder."
    },
    {
        Name: "PLUT",
        Color: "rgb(100, 100, 44)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Light: false,
        Temp: 46,
        Type: "Powder",
        Category: "Powder",
        Description: "Highly radioactive powder."
    },
    {
        Name: "NEUT",
        Color: "rgb(32, 224, 255)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Light: true,
        Temp: 22,
        Type: "None",
        Category: "None",
        Description: "Radioactive and glowing."
    },
    {
        Name: "PHOT",
        Color: "rgb(255, 255, 255)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: true,
        Temp: 500,
        Type: "None",
        Category: "None",
        Description: "High-temperature light."
    },
    {
        Name: "STNE",
        Color: "rgb(155, 155, 155)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Powder",
        Category: "Powder",
        Description: "Stone-like powder."
    },
    {
        Name: "SALT",
        Color: "rgb(225, 225, 225)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Powder",
        Category: "Powder",
        Description: "Seasoning powder."
    },
    {
        Name: "OXYG",
        Color: "rgb(200, 200, 255)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Gas",
        Category: "Gas",
        Description: "Supports combustion."
    },
    {
        Name: "FIRE",
        Color: "rgb(255, 50, 50)",
        Flammable: false,
        Caustic: true,
        Radioactive: false,
        Light: false,
        Temp: 500,
        Type: "Gas",
        Category: "Gas",
        Description: "Hot, caustic gas."
    },
    {
        Name: "SMKE",
        Color: "rgb(100, 100, 100)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 250,
        Type: "Gas",
        Category: "Gas",
        Description: "Dense smoke."
    },
    {
        Name: "NONE",
        Color: "rgb(0, 0, 0)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 0,
        Type: "None",
        Category: "None",
        Description: "No substance."
    }
];
