export const Elements = [
    {
        Name: "SAND",
        Color: "rgb(194, 178, 128)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Powder",
        Category: "Powder",
        Flair: "Powder"
    },
    {
        Name: "WATR",
        Color: "rgb(15, 94, 156)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 32,
        Type: "Liquid",
        Category: "Liquid",
        Flair: "Liquid"
    },
    {
        Name: "COAL",
        Color: "rgb(68, 69, 69)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "WOOD",
        Color: "rgb(218, 109, 66)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "IRON",
        Color: "rgb(60, 60, 60)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "BRCK",
        Color: "rgb(90, 90, 90)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "GOLD",
        Color: "rgb(255, 165, 0)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "TTAN",
        Color: "rgb(144, 144, 144)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Solid",
        Category: "Solid",
        Flair: "Solid"
    },
    {
        Name: "SNOW",
        Color: "rgb(134, 214, 216)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 0,
        Type: "Powder",
        Category: "Powder",
        Flair: "Powder"
    },
    {
        Name: "BCOL",
        Color: "rgb(69, 69, 69)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Powder",
        Category: "Powder",
        Flair: "Powder"
    },
    {
        Name: "URAN",
        Color: "rgb(112, 112, 32)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Light: false,
        Temp: 46,
        Type: "Powder",
        Category: "Powder",
        Flair: "Radioactive Powder"
    },
    {
        Name: "ROEN",
        Color: "rgb(100, 124, 32)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Light: false,
        Temp: 46,
        Type: "Powder",
        Category: "Powder",
        Flair: "Radioactive Powder"
    },
    {
        Name: "PLUT",
        Color: "rgb(70, 150, 22)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Light: false,
        Temp: 46,
        Type: "Powder",
        Category: "Powder",
        Flair: "Radioactive Powder"
    },
    {
        Name: "NEUT",
        Color: "rgb(32, 224, 255)",
        Flammable: false,
        Caustic: false,
        Radioactive: true,
        Light: true,
        Temp: 22,
        Type: "None",
        Category: "None",
        Flair: "Radioactive Light"
    },
    {
        Name: "PHOT",
        Color: "rgb(255, 255, 255)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: true,
        Temp: 500,
        Type: "None",
        Category: "None",
        Flair: "Visible Light"
    },
    {
        Name: "STNE",
        Color: "rgb(155, 155, 155)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Powder",
        Category: "Powder",
        Flair: "Powder"
    },
    {
        Name: "SALT",
        Color: "rgb(225, 225, 225)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Powder",
        Category: "Powder",
        Flair: "Powder"
    },
    {
        Name: "OXYG",
        Color: "rgb(200, 200, 255)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Gas",
        Category: "Gas",
        Flair: "Gas"
    },
    {
        Name: "HYGN",
        Color: "rgb(80, 112, 255)",
        Flammable: true,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 22,
        Type: "Gas",
        Category: "Gas",
        Flair: "Gas"
    },
    {
        Name: "FIRE",
        Color: "rgb(255, 50, 50)",
        Flammable: false,
        Caustic: true,
        Radioactive: false,
        Light: false,
        Temp: 1100,
        Type: "Gas",
        Category: "Gas",
        Flair: "Caustic Gas"
    },
    {
        Name: "SMKE",
        Color: "rgb(100, 100, 100)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 149,
        Type: "Gas",
        Category: "Gas",
        Flair: "Dense Gas"
    },
    {
        Name: "NONE",
        Color: "rgb(0, 0, 0)",
        Flammable: false,
        Caustic: false,
        Radioactive: false,
        Light: false,
        Temp: 0,
        Type: "None",
        Category: "None",
        Flair: "None"
    }
];